### ISSUE TITLE
Comprehensive refactoring – tracking issue

### ISSUE THREAD

**Issue by xplosionmind** [xplosionmind/tommi.space#121]
For the past two weeks I have been comprehensively refactoring the code of `tommi.space`, and, despite my best intentions, I did *not* use explanatory commit messages, hell, not even any kind of criteria for the things I was changing.

Even if it’s late, I am creating this issue to track the last touch-ups to be made.

- [x] `.wavyBackground`s for headers
   - embed the SVG in the CSS or link the file?
   - consistent color-labelling
- [ ] Sort and cleanup CSS following [CUBE](https://cube.fyi) criteria
- [ ] Jam pages cleanup
- [x] Adjust feeds pages
- [ ] Adjust pages with `main.list`
   - What if they have a subheading outside `.e-content`?
- [ ] Sconnesso layout
- [x] Fix search
- [x] BUG: Zibaldone overflow
