### ISSUE TITLE
Migrating to ESM and 11ty v3 – tracking issue

### ISSUE THREAD

**Issue by xplosionmind** [xplosionmind/tommi.space#127]
I am having a very hard time migrating this project to ECMAScript Modules. I would love to [get some help](https://pan.rent/@tommi/112947242998520661 '🎈 Looking for help from fellow Eleventy users! 👀 – Fediverse post on pan.rent')!

Changes are happening in [the `11ty-v3` branch](https://github.com/xplosionmind/tommi.space/tree/11ty-v3).

A summary of the current blockers:

- [x] [CSV data files support](https://github.com/11ty/eleventy/discussions/3413)
- [x] [eleventy-sass plugin](https://github.com/kentaroi/eleventy-sass 'eleventy-sass repository on GitHub') [does not support 11ty v3](https://github.com/kentaroi/eleventy-sass/issues/30 '11ty 3.0, version specifier and ESM – GitHub issue') yet
- [x] Using [eleventy-img](https://github.com/11ty/eleventy-img 'eleventy-img repository on GitHub') [version 5](https://github.com/11ty/eleventy-img/releases/tag/v5.0.0-beta.10 'Eleventy Image v5.0.0-beta.10 release on GitHub')
- [x] Configure [`IdAttribute` plugin](https://github.com/11ty/eleventy/issues/3363) to automatically add `<a>` tags to headings, too
- [x] Replace wikilinks with regular Markdown links. Blocked by: https://github.com/11ty/eleventy/issues/3417

**Comment by xplosionmind** [comment]
Done a couple of years ago already, but I forgot to close this issue.
