### ISSUE TITLE
Improve Wikilinks implementation

### ISSUE THREAD

**Issue by xplosionmind** [xplosionmind/tommi.space#14]
As of right now, the use of wikilinks is strictly limited to and by the [markdown-it-wikilinks](https://github.com/jsepia/markdown-it-wikilinks) feature set.

Missing features I intend to use:
- [ ] jsepia/markdown-it-wikilinks#7
- [ ] jsepia/markdown-it-wikilinks#8
- [ ] jsepia/markdown-it-wikilinks#9
- [ ] jsepia/markdown-it-wikilinks#10

**Comment by xplosionmind** [comment]
Now using standard Markdown links instead of wikilinks, and not using the markdown-it-wikilinks plugin anymore.
